//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Vote {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Vote() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Vote", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        internal static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة تصويت.
        /// </summary>
        internal static string AdminPageAdd {
            get {
                return ResourceManager.GetString("AdminPageAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض التصويتات.
        /// </summary>
        internal static string AdminPageDefault {
            get {
                return ResourceManager.GetString("AdminPageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الإختيارات.
        /// </summary>
        internal static string AnswersCount {
            get {
                return ResourceManager.GetString("AnswersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإختيار.
        /// </summary>
        internal static string AnswerText {
            get {
                return ResourceManager.GetString("AnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عودة.
        /// </summary>
        internal static string btnBackText {
            get {
                return ResourceManager.GetString("btnBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصويت.
        /// </summary>
        internal static string btnVoteText {
            get {
                return ResourceManager.GetString("btnVoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ إغلاق التصويت.
        /// </summary>
        internal static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تارخ الإضافة.
        /// </summary>
        internal static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق التصويت.
        /// </summary>
        internal static string IsClosed {
            get {
                return ResourceManager.GetString("IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصويت رئيسي.
        /// </summary>
        internal static string IsMain {
            get {
                return ResourceManager.GetString("IsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستطلاعات سابقة.
        /// </summary>
        internal static string PreviousVotes {
            get {
                return ResourceManager.GetString("PreviousVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال.
        /// </summary>
        internal static string QuestionText {
            get {
                return ResourceManager.GetString("QuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النتيجة.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        internal static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أغلق.
        /// </summary>
        internal static string Status_Close {
            get {
                return ResourceManager.GetString("Status_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلق.
        /// </summary>
        internal static string Status_Closed {
            get {
                return ResourceManager.GetString("Status_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to في إنتظار التفعيل.
        /// </summary>
        internal static string Status_Waiting {
            get {
                return ResourceManager.GetString("Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكرا علي التصويت.
        /// </summary>
        internal static string Thanks4Voting {
            get {
                return ResourceManager.GetString("Thanks4Voting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإختيارات.
        /// </summary>
        internal static string VoteAnswers {
            get {
                return ResourceManager.GetString("VoteAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصويت .
        /// </summary>
        internal static string VoteModuleTitle {
            get {
                return ResourceManager.GetString("VoteModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة الإستفتاء.
        /// </summary>
        internal static string VoteResult {
            get {
                return ResourceManager.GetString("VoteResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأصوات.
        /// </summary>
        internal static string VoteResult_HitsCount {
            get {
                return ResourceManager.GetString("VoteResult_HitsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجمالى الأصوات:.
        /// </summary>
        internal static string VoteResult_TotalHits {
            get {
                return ResourceManager.GetString("VoteResult_TotalHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد قمت بالتصويت من قبل.
        /// </summary>
        internal static string YouAlreadyVoted {
            get {
                return ResourceManager.GetString("YouAlreadyVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار اجابة.
        /// </summary>
        internal static string YouMustChooseChoice {
            get {
                return ResourceManager.GetString("YouMustChooseChoice", resourceCulture);
            }
        }
    }
}
