//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultModules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultModules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DefaultModules", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_About_Us {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Advertisments {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Advertisments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكتاب.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Authors {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفعاليات والأحداث.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Calendar {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشارات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Consulting_Services {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Consulting_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتصل بنا.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Contact_Us {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة البريدية.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_MailList {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_MailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخبار.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_News {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرض الصور.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_PhotoGallery {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_PhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في الموقع  .
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Registration {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشاريين.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Registration_Consultant {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Registration_Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في الموقع.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Registration_User {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Registration_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى الثابت.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_SitePages {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_SitePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوال الموقع.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_SMS {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعضاء الرابطة.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_SubAdmins {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_SubAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Subscribtion {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Subscribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعريف بالأعضاء.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_UsersProfiles {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_UsersProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع الزوار.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_VisitorSigns {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_VisitorSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستبيان.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Vote {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        internal static string ModuleTitle_About_Us {
            get {
                return ResourceManager.GetString("ModuleTitle_About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات.
        /// </summary>
        internal static string ModuleTitle_Advertisments {
            get {
                return ResourceManager.GetString("ModuleTitle_Advertisments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكتاب.
        /// </summary>
        internal static string ModuleTitle_Authors {
            get {
                return ResourceManager.GetString("ModuleTitle_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفعاليات والأحداث.
        /// </summary>
        internal static string ModuleTitle_Calendar {
            get {
                return ResourceManager.GetString("ModuleTitle_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشارات.
        /// </summary>
        internal static string ModuleTitle_Consulting_Services {
            get {
                return ResourceManager.GetString("ModuleTitle_Consulting_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتصل بنا.
        /// </summary>
        internal static string ModuleTitle_Contact_Us {
            get {
                return ResourceManager.GetString("ModuleTitle_Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة البريدية.
        /// </summary>
        internal static string ModuleTitle_MailList {
            get {
                return ResourceManager.GetString("ModuleTitle_MailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخبار.
        /// </summary>
        internal static string ModuleTitle_News {
            get {
                return ResourceManager.GetString("ModuleTitle_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرض الصور.
        /// </summary>
        internal static string ModuleTitle_PhotoGallery {
            get {
                return ResourceManager.GetString("ModuleTitle_PhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في الموقع  .
        /// </summary>
        internal static string ModuleTitle_Registration {
            get {
                return ResourceManager.GetString("ModuleTitle_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشاريين.
        /// </summary>
        internal static string ModuleTitle_Registration_Consultant {
            get {
                return ResourceManager.GetString("ModuleTitle_Registration_Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في الموقع.
        /// </summary>
        internal static string ModuleTitle_Registration_User {
            get {
                return ResourceManager.GetString("ModuleTitle_Registration_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى الثابت.
        /// </summary>
        internal static string ModuleTitle_SitePages {
            get {
                return ResourceManager.GetString("ModuleTitle_SitePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوال الموقع.
        /// </summary>
        internal static string ModuleTitle_SMS {
            get {
                return ResourceManager.GetString("ModuleTitle_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعضاء الرابطة.
        /// </summary>
        internal static string ModuleTitle_SubAdmins {
            get {
                return ResourceManager.GetString("ModuleTitle_SubAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        internal static string ModuleTitle_Subscribtion {
            get {
                return ResourceManager.GetString("ModuleTitle_Subscribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعريف بالأعضاء.
        /// </summary>
        internal static string ModuleTitle_UsersProfiles {
            get {
                return ResourceManager.GetString("ModuleTitle_UsersProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع الزوار.
        /// </summary>
        internal static string ModuleTitle_VisitorSigns {
            get {
                return ResourceManager.GetString("ModuleTitle_VisitorSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستبيان.
        /// </summary>
        internal static string ModuleTitle_Vote {
            get {
                return ResourceManager.GetString("ModuleTitle_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة تصنيف.
        /// </summary>
        internal static string Module_CategoriesAdd {
            get {
                return ResourceManager.GetString("Module_CategoriesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيفات.
        /// </summary>
        internal static string Module_CategoriesDefault {
            get {
                return ResourceManager.GetString("Module_CategoriesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل تصنيف.
        /// </summary>
        internal static string Module_CategoriesEdit {
            get {
                return ResourceManager.GetString("Module_CategoriesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        internal static string Module_Comments {
            get {
                return ResourceManager.GetString("Module_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات المفعلة.
        /// </summary>
        internal static string Module_CommentsActive {
            get {
                return ResourceManager.GetString("Module_CommentsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات غير المفعلة.
        /// </summary>
        internal static string Module_CommentsInactive {
            get {
                return ResourceManager.GetString("Module_CommentsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string Module_ItemsAdd {
            get {
                return ResourceManager.GetString("Module_ItemsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        internal static string Module_ItemsDefault {
            get {
                return ResourceManager.GetString("Module_ItemsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Module_ItemsEdit {
            get {
                return ResourceManager.GetString("Module_ItemsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصور.
        /// </summary>
        internal static string Module_ItemsPhotos {
            get {
                return ResourceManager.GetString("Module_ItemsPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة صورة.
        /// </summary>
        internal static string Module_ItemsPhotosAdd {
            get {
                return ResourceManager.GetString("Module_ItemsPhotosAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بياناتي.
        /// </summary>
        internal static string MyProfileData {
            get {
                return ResourceManager.GetString("MyProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث.
        /// </summary>
        internal static string PageTitle_Search {
            get {
                return ResourceManager.GetString("PageTitle_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خريطة الموقع.
        /// </summary>
        internal static string PageTitle_SiteMap {
            get {
                return ResourceManager.GetString("PageTitle_SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف بالعضو.
        /// </summary>
        internal static string PageTitle_UserProfilePage {
            get {
                return ResourceManager.GetString("PageTitle_UserProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string _Home {
            get {
                return ResourceManager.GetString("_Home", resourceCulture);
            }
        }
    }
}
