//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.User", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف تعليقك.
        /// </summary>
        internal static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الإضافة بنجاح.
        /// </summary>
        internal static string AddingOperationDone {
            get {
                return ResourceManager.GetString("AddingOperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الإضافة.
        /// </summary>
        internal static string AddingOperationFaild {
            get {
                return ResourceManager.GetString("AddingOperationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف الصفحة في الفيس بوك.
        /// </summary>
        internal static string AddToFacebook {
            get {
                return ResourceManager.GetString("AddToFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضف الى المفضلة.
        /// </summary>
        internal static string AddToFav {
            get {
                return ResourceManager.GetString("AddToFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفضلتك علي  Myspace.
        /// </summary>
        internal static string AddToMyspace {
            get {
                return ResourceManager.GetString("AddToMyspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف الصفحة  في تويتر.
        /// </summary>
        internal static string AddToTwitter {
            get {
                return ResourceManager.GetString("AddToTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل كود التأكيد.
        /// </summary>
        internal static string CapatchaRequied {
            get {
                return ResourceManager.GetString("CapatchaRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل كود التأكيد.
        /// </summary>
        internal static string CapatchaText {
            get {
                return ResourceManager.GetString("CapatchaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود التأكيد خاطئ.
        /// </summary>
        internal static string CapatchInvalid {
            get {
                return ResourceManager.GetString("CapatchInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر.
        /// </summary>
        internal static string Choose1 {
            get {
                return ResourceManager.GetString("Choose1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضغط لتحميل الملف .
        /// </summary>
        internal static string ClickToDownload {
            get {
                return ResourceManager.GetString("ClickToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضغط لتكبير الصورة.
        /// </summary>
        internal static string ClickToEnlarge {
            get {
                return ResourceManager.GetString("ClickToEnlarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة.
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة/إنهاء.
        /// </summary>
        internal static string CreateThenFinish {
            get {
                return ResourceManager.GetString("CreateThenFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة/جديد.
        /// </summary>
        internal static string CreateThenNew {
            get {
                return ResourceManager.GetString("CreateThenNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        internal static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم.
        /// </summary>
        internal static string DateControl_Day {
            get {
                return ResourceManager.GetString("DateControl_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to م.
        /// </summary>
        internal static string DateControl_Georgian {
            get {
                return ResourceManager.GetString("DateControl_Georgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ه.
        /// </summary>
        internal static string DateControl_Islamic {
            get {
                return ResourceManager.GetString("DateControl_Islamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشهر.
        /// </summary>
        internal static string DateControl_Month {
            get {
                return ResourceManager.GetString("DateControl_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة.
        /// </summary>
        internal static string DateControl_Year {
            get {
                return ResourceManager.GetString("DateControl_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من إتمام عملية الحذف ؟.
        /// </summary>
        internal static string DeleteActivation {
            get {
                return ResourceManager.GetString("DeleteActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحذف بنجاح.
        /// </summary>
        internal static string DeletingOprationDone {
            get {
                return ResourceManager.GetString("DeletingOprationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الحذف.
        /// </summary>
        internal static string DeletingOprationFaild {
            get {
                return ResourceManager.GetString("DeletingOprationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        internal static string DownLoad {
            get {
                return ResourceManager.GetString("DownLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        internal static string DownLoadExistFile {
            get {
                return ResourceManager.GetString("DownLoadExistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا - الملف غير موجود.
        /// </summary>
        internal static string DownLoad_FileNotFound {
            get {
                return ResourceManager.GetString("DownLoad_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل مكرر.
        /// </summary>
        internal static string DuplicateItem {
            get {
                return ResourceManager.GetString("DuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اذا لم يظهر المشغل برجاء تحميله من.
        /// </summary>
        internal static string GetObject {
            get {
                return ResourceManager.GetString("GetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميل خاطئ.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوجو المرفوع ليس صورة.
        /// </summary>
        internal static string InvalidLogoFile {
            get {
                return ResourceManager.GetString("InvalidLogoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل قيمة رقمية.
        /// </summary>
        internal static string InvalidNumericalData {
            get {
                return ResourceManager.GetString("InvalidNumericalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف المرفوع ليس صورة.
        /// </summary>
        internal static string InvalidPhotoFile {
            get {
                return ResourceManager.GetString("InvalidPhotoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المراجعة.
        /// </summary>
        internal static string IsSeen {
            get {
                return ResourceManager.GetString("IsSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللوجو.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموافق.
        /// </summary>
        internal static string Mofeq {
            get {
                return ResourceManager.GetString("Mofeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد ....
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد لوجو.
        /// </summary>
        internal static string NoLogo {
            get {
                return ResourceManager.GetString("NoLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد صورة.
        /// </summary>
        internal static string NoPhoto {
            get {
                return ResourceManager.GetString("NoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن فقط رفع هذة الإمتدادات لملف الصوت .
        /// </summary>
        internal static string NotSuportedAudioExtention {
            get {
                return ResourceManager.GetString("NotSuportedAudioExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن فقط رفع هذة الإمتدادات للملف .
        /// </summary>
        internal static string NotSuportedFileExtention {
            get {
                return ResourceManager.GetString("NotSuportedFileExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن فقط رفع هذة الإمتدادات لملف الفيديو .
        /// </summary>
        internal static string NotSuportedVideoExtention {
            get {
                return ResourceManager.GetString("NotSuportedVideoExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string OtherLang {
            get {
                return ResourceManager.GetString("OtherLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Website/Languages/LangSpecification.aspx?LangID=2.
        /// </summary>
        internal static string OtherLangLink {
            get {
                return ResourceManager.GetString("OtherLangLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأول.
        /// </summary>
        internal static string PagerFrist {
            get {
                return ResourceManager.GetString("PagerFrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من.
        /// </summary>
        internal static string PagerFrom {
            get {
                return ResourceManager.GetString("PagerFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخير.
        /// </summary>
        internal static string PagerLast {
            get {
                return ResourceManager.GetString("PagerLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        internal static string PagerNext {
            get {
                return ResourceManager.GetString("PagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة.
        /// </summary>
        internal static string PagerPageNO {
            get {
                return ResourceManager.GetString("PagerPageNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        internal static string PagerPrevious {
            get {
                return ResourceManager.GetString("PagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقييم المحتوى.
        /// </summary>
        internal static string RateThisItem {
            get {
                return ResourceManager.GetString("RateThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إقـرأ المزيـد.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان مطلوب.
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string RequiredField1 {
            get {
                return ResourceManager.GetString("RequiredField1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة Rss.
        /// </summary>
        internal static string Rss {
            get {
                return ResourceManager.GetString("Rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الحفظ.
        /// </summary>
        internal static string SavingDataFaild {
            get {
                return ResourceManager.GetString("SavingDataFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحفظ.
        /// </summary>
        internal static string SavingDataSuccessfuly {
            get {
                return ResourceManager.GetString("SavingDataSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        internal static string Search_All {
            get {
                return ResourceManager.GetString("Search_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء عملية الإرسال حاول مرة أخرى.
        /// </summary>
        internal static string SendingOperationFaild {
            get {
                return ResourceManager.GetString("SendingOperationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رسالة.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارك.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخبر صديق.
        /// </summary>
        internal static string TellAFriend {
            get {
                return ResourceManager.GetString("TellAFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكرأ.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات.
        /// </summary>
        internal static string ThereIsNoData {
            get {
                return ResourceManager.GetString("ThereIsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجمالي التعليقات.
        /// </summary>
        internal static string TotalComments {
            get {
                return ResourceManager.GetString("TotalComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية التعديل.
        /// </summary>
        internal static string UpdatingOperationFaild {
            get {
                return ResourceManager.GetString("UpdatingOperationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التعديل.
        /// </summary>
        internal static string UpdatingsOperationDone {
            get {
                return ResourceManager.GetString("UpdatingsOperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التعديل.
        /// </summary>
        internal static string UpdatingsOperationDone1 {
            get {
                return ResourceManager.GetString("UpdatingsOperationDone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقصى مساحة مسموحة لملف الصوت .
        /// </summary>
        internal static string UploadedAudioGreaterThanMaxLength {
            get {
                return ResourceManager.GetString("UploadedAudioGreaterThanMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقصى مساحة مسموحة للملف .
        /// </summary>
        internal static string UploadedFileGreaterThanMaxLength {
            get {
                return ResourceManager.GetString("UploadedFileGreaterThanMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقصى مساحة مسموحة لملف الفيديو .
        /// </summary>
        internal static string UploadedVideoGreaterThanMaxLength {
            get {
                return ResourceManager.GetString("UploadedVideoGreaterThanMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زائـر.
        /// </summary>
        internal static string Visitor {
            get {
                return ResourceManager.GetString("Visitor", resourceCulture);
            }
        }
    }
}
