//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النشاط.
        /// </summary>
        internal static string ActivitiesID {
            get {
                return ResourceManager.GetString("ActivitiesID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صناعة.
        /// </summary>
        internal static string ActivitiesID_1 {
            get {
                return ResourceManager.GetString("ActivitiesID_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجارة.
        /// </summary>
        internal static string ActivitiesID_2 {
            get {
                return ResourceManager.GetString("ActivitiesID_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقاولات.
        /// </summary>
        internal static string ActivitiesID_3 {
            get {
                return ResourceManager.GetString("ActivitiesID_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالية.
        /// </summary>
        internal static string ActivitiesID_4 {
            get {
                return ResourceManager.GetString("ActivitiesID_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عقار.
        /// </summary>
        internal static string ActivitiesID_5 {
            get {
                return ResourceManager.GetString("ActivitiesID_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسويق.
        /// </summary>
        internal static string ActivitiesID_6 {
            get {
                return ResourceManager.GetString("ActivitiesID_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات.
        /// </summary>
        internal static string ActivitiesID_7 {
            get {
                return ResourceManager.GetString("ActivitiesID_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        internal static string ActivitiesID_8 {
            get {
                return ResourceManager.GetString("ActivitiesID_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمر.
        /// </summary>
        internal static string AgeRang {
            get {
                return ResourceManager.GetString("AgeRang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحت العشرين.
        /// </summary>
        internal static string AgeRang_1 {
            get {
                return ResourceManager.GetString("AgeRang_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20-30.
        /// </summary>
        internal static string AgeRang_2 {
            get {
                return ResourceManager.GetString("AgeRang_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30-40.
        /// </summary>
        internal static string AgeRang_3 {
            get {
                return ResourceManager.GetString("AgeRang_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40-50.
        /// </summary>
        internal static string AgeRang_4 {
            get {
                return ResourceManager.GetString("AgeRang_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فوق الخمسين.
        /// </summary>
        internal static string AgeRang_5 {
            get {
                return ResourceManager.GetString("AgeRang_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الرسائل.
        /// </summary>
        internal static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الصوتي.
        /// </summary>
        internal static string AudioExtension {
            get {
                return ResourceManager.GetString("AudioExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        internal static string CategoryID {
            get {
                return ResourceManager.GetString("CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        internal static string CityID {
            get {
                return ResourceManager.GetString("CityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الشركة.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        internal static string CountryID {
            get {
                return ResourceManager.GetString("CountryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رسالة.
        /// </summary>
        internal static string CreateMessages {
            get {
                return ResourceManager.GetString("CreateMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإرسال.
        /// </summary>
        internal static string DateAdded {
            get {
                return ResourceManager.GetString("DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإرسال.
        /// </summary>
        internal static string Date_Added {
            get {
                return ResourceManager.GetString("Date_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى لتعليمي.
        /// </summary>
        internal static string EducationLevel {
            get {
                return ResourceManager.GetString("EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إبتدائي.
        /// </summary>
        internal static string EducationLevel_1 {
            get {
                return ResourceManager.GetString("EducationLevel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوسط.
        /// </summary>
        internal static string EducationLevel_2 {
            get {
                return ResourceManager.GetString("EducationLevel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثانوي.
        /// </summary>
        internal static string EducationLevel_3 {
            get {
                return ResourceManager.GetString("EducationLevel_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دراسات عليا ماجستير.
        /// </summary>
        internal static string EducationLevel_4 {
            get {
                return ResourceManager.GetString("EducationLevel_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دراسات عليا دكتوراه.
        /// </summary>
        internal static string EducationLevel_5 {
            get {
                return ResourceManager.GetString("EducationLevel_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الوظيفي.
        /// </summary>
        internal static string EmpNo {
            get {
                return ResourceManager.GetString("EmpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل قيمة رقمية.
        /// </summary>
        internal static string EmpNoError {
            get {
                return ResourceManager.GetString("EmpNoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاكس.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        internal static string FileExtension {
            get {
                return ResourceManager.GetString("FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأول.
        /// </summary>
        internal static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        internal static string Gender_1 {
            get {
                return ResourceManager.GetString("Gender_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        internal static string Gender_2 {
            get {
                return ResourceManager.GetString("Gender_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط العرض.
        /// </summary>
        internal static string GoogleLatitude {
            get {
                return ResourceManager.GetString("GoogleLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط الطول.
        /// </summary>
        internal static string GoogleLongitude {
            get {
                return ResourceManager.GetString("GoogleLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإشتراك في القائمة البريدية.
        /// </summary>
        internal static string HasEmailService {
            get {
                return ResourceManager.GetString("HasEmailService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمات المرغوب الإشتراك فيها.
        /// </summary>
        internal static string HasServices {
            get {
                return ResourceManager.GetString("HasServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإشتراك في خدمة الجوال.
        /// </summary>
        internal static string HasSmsService {
            get {
                return ResourceManager.GetString("HasSmsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطول.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ibtnMsgSending.
        /// </summary>
        internal static string ibtnMsgSendingClass {
            get {
                return ResourceManager.GetString("ibtnMsgSendingClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض عام على الموقع.
        /// </summary>
        internal static string IsAvailable {
            get {
                return ResourceManager.GetString("IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة العرض.
        /// </summary>
        internal static string IsAvailable_Status {
            get {
                return ResourceManager.GetString("IsAvailable_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئيسي.
        /// </summary>
        internal static string IsMain {
            get {
                return ResourceManager.GetString("IsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الرد.
        /// </summary>
        internal static string IsReplied {
            get {
                return ResourceManager.GetString("IsReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المراجعة.
        /// </summary>
        internal static string IsSeen {
            get {
                return ResourceManager.GetString("IsSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        internal static string ItemDate {
            get {
                return ResourceManager.GetString("ItemDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمل.
        /// </summary>
        internal static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة.
        /// </summary>
        internal static string JobID {
            get {
                return ResourceManager.GetString("JobID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تليفون العمل.
        /// </summary>
        internal static string JobTel {
            get {
                return ResourceManager.GetString("JobTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة.
        /// </summary>
        internal static string JobText {
            get {
                return ResourceManager.GetString("JobText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثالث.
        /// </summary>
        internal static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق بريد.
        /// </summary>
        internal static string MailBox {
            get {
                return ResourceManager.GetString("MailBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسائل.
        /// </summary>
        internal static string MessagesBoxHeader {
            get {
                return ResourceManager.GetString("MessagesBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسائل.
        /// </summary>
        internal static string MessagesModuleTitle {
            get {
                return ResourceManager.GetString("MessagesModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكلمات المفتاحية.
        /// </summary>
        internal static string MetaKeyWords {
            get {
                return ResourceManager.GetString("MetaKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثاني.
        /// </summary>
        internal static string Mname {
            get {
                return ResourceManager.GetString("Mname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الرسائل.
        /// </summary>
        internal static string Module_AllMessage {
            get {
                return ResourceManager.GetString("Module_AllMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة تصنيف.
        /// </summary>
        internal static string Module_CategoriesAdd {
            get {
                return ResourceManager.GetString("Module_CategoriesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيفات.
        /// </summary>
        internal static string Module_CategoriesDefault {
            get {
                return ResourceManager.GetString("Module_CategoriesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل تصنيف.
        /// </summary>
        internal static string Module_CategoriesEdit {
            get {
                return ResourceManager.GetString("Module_CategoriesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        internal static string Module_Comments {
            get {
                return ResourceManager.GetString("Module_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات المفعلة.
        /// </summary>
        internal static string Module_CommentsActive {
            get {
                return ResourceManager.GetString("Module_CommentsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات غير المفعلة.
        /// </summary>
        internal static string Module_CommentsInactive {
            get {
                return ResourceManager.GetString("Module_CommentsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير البيانات.
        /// </summary>
        internal static string Module_ExportData {
            get {
                return ResourceManager.GetString("Module_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير البيانات.
        /// </summary>
        internal static string Module_ExportData1 {
            get {
                return ResourceManager.GetString("Module_ExportData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string Module_ItemsAdd {
            get {
                return ResourceManager.GetString("Module_ItemsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        internal static string Module_ItemsDefault {
            get {
                return ResourceManager.GetString("Module_ItemsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Module_ItemsEdit {
            get {
                return ResourceManager.GetString("Module_ItemsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصور.
        /// </summary>
        internal static string Module_ItemsPhotos {
            get {
                return ResourceManager.GetString("Module_ItemsPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة صورة.
        /// </summary>
        internal static string Module_ItemsPhotosAdd {
            get {
                return ResourceManager.GetString("Module_ItemsPhotosAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الرسالة.
        /// </summary>
        internal static string Module_MessageData {
            get {
                return ResourceManager.GetString("Module_MessageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد الرسائل.
        /// </summary>
        internal static string Module_NewMessage {
            get {
                return ResourceManager.GetString("Module_NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        internal static string NationalityID {
            get {
                return ResourceManager.GetString("NationalityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالة جديدة.
        /// </summary>
        internal static string NewMessageRecieved {
            get {
                return ResourceManager.GetString("NewMessageRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes1.
        /// </summary>
        internal static string Notes1 {
            get {
                return ResourceManager.GetString("Notes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes2.
        /// </summary>
        internal static string Notes2 {
            get {
                return ResourceManager.GetString("Notes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض للمسجلين فقط.
        /// </summary>
        internal static string OnlyForRegisered {
            get {
                return ResourceManager.GetString("OnlyForRegisered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة السجل.
        /// </summary>
        internal static string Photo2Extension {
            get {
                return ResourceManager.GetString("Photo2Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        internal static string PhotoExtension {
            get {
                return ResourceManager.GetString("PhotoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أولوية العرض.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishAudio {
            get {
                return ResourceManager.GetString("PublishAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishFile {
            get {
                return ResourceManager.GetString("PublishFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishPhoto {
            get {
                return ResourceManager.GetString("PublishPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishPhoto2 {
            get {
                return ResourceManager.GetString("PublishPhoto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishVideo {
            get {
                return ResourceManager.GetString("PublishVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishYoutbe {
            get {
                return ResourceManager.GetString("PublishYoutbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرد.
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الرد.
        /// </summary>
        internal static string ReplyDate {
            get {
                return ResourceManager.GetString("ReplyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رداً على رسالتك.
        /// </summary>
        internal static string ReplyMailSubject {
            get {
                return ResourceManager.GetString("ReplyMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال إميلات.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إستقبال رسالتكم نشكركم على تواصلكم معنا.
        /// </summary>
        internal static string SendinogOperationDone {
            get {
                return ResourceManager.GetString("SendinogOperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تنجح عملية إرسال رسالتك من فضلك حاول في وقت أخر.
        /// </summary>
        internal static string SendinogOperationFaild {
            get {
                return ResourceManager.GetString("SendinogOperationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب إستشارة.
        /// </summary>
        internal static string SendPageTitle {
            get {
                return ResourceManager.GetString("SendPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رسائل قصيرة.
        /// </summary>
        internal static string SendSms {
            get {
                return ResourceManager.GetString("SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نبذة.
        /// </summary>
        internal static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشكركم على التواصل سيتم مراجعة التوقيع قبل عرضه.
        /// </summary>
        internal static string SiteVisitors {
            get {
                return ResourceManager.GetString("SiteVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة الإجتماعية.
        /// </summary>
        internal static string SocialStatus {
            get {
                return ResourceManager.GetString("SocialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متزوج / متزوجة.
        /// </summary>
        internal static string SocialStatus_1 {
            get {
                return ResourceManager.GetString("SocialStatus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعزب / أنسة.
        /// </summary>
        internal static string SocialStatus_2 {
            get {
                return ResourceManager.GetString("SocialStatus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلق / مطلقة.
        /// </summary>
        internal static string SocialStatus_3 {
            get {
                return ResourceManager.GetString("SocialStatus_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرمل / أرملة.
        /// </summary>
        internal static string SocialStatus_4 {
            get {
                return ResourceManager.GetString("SocialStatus_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال إلى.
        /// </summary>
        internal static string ToItemID {
            get {
                return ResourceManager.GetString("ToItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال إلى.
        /// </summary>
        internal static string ToUserID {
            get {
                return ResourceManager.GetString("ToUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الرسالة.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكوى.
        /// </summary>
        internal static string Type_1 {
            get {
                return ResourceManager.GetString("Type_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستفسار.
        /// </summary>
        internal static string Type_2 {
            get {
                return ResourceManager.GetString("Type_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليق.
        /// </summary>
        internal static string Type_3 {
            get {
                return ResourceManager.GetString("Type_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستفسار.
        /// </summary>
        internal static string Type_4 {
            get {
                return ResourceManager.GetString("Type_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير محدد.
        /// </summary>
        internal static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الرسالة.
        /// </summary>
        internal static string UpdateMessages {
            get {
                return ResourceManager.GetString("UpdateMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع الإلكتروني.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        internal static string UserCityName {
            get {
                return ResourceManager.GetString("UserCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف المرئي.
        /// </summary>
        internal static string VideoExtension {
            get {
                return ResourceManager.GetString("VideoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الزيارات.
        /// </summary>
        internal static string VisitiesCount {
            get {
                return ResourceManager.GetString("VisitiesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العرض.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود ملف اليوتيوب.
        /// </summary>
        internal static string YoutubeCode {
            get {
                return ResourceManager.GetString("YoutubeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز البريدي.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
