function remIE(url,width,height)
{
	document.write('<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0"   id="head" width="'+width+'" height="'+height+'"><param name="movie" value="'+url+'"><param name="menu" value="0"><param name="quality" value="high"><param name="wmode" value="transparent"><param name="allowscriptaccess" value="samedomain"><embed type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" name="head" width="'+width+'" height="'+height+'" src="'+url+'" menu="0" quality="high" allowscriptaccess="samedomain" wmode="transparent"></embed></object>');
}
function remIENoWH(url) {
    document.write('<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0"   id="head" width="' + width + '" height="' + height + '"><param name="movie" value="' + url + '"><param name="menu" value="0"><param name="quality" value="high"><param name="wmode" value="transparent"><param name="allowscriptaccess" value="samedomain"><embed type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" name="head"  src="' + url + '" menu="0" quality="high" allowscriptaccess="samedomain" wmode="transparent"></embed></object>');
}
function remIEWindow(url,width,height)
{
	document.write('<object style="border:solid #555555 0px;backgroud-color:blue;" id=FLAOBJ classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,19,0" width="'+width+'" height="'+height+'" align="middle"><param name="allowScriptAccess" value="sameDomain" /><param name="wmode" value="Window" /><param name="movie" value="'+url+'" /><param name="menu" value="0" /><param name="quality" value="high" /><param name="allowFullScreen" value="true" /><embed type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" name="head" width="'+width+'" height="'+height+'" src="'+url+'" menu="0" quality="high" allowscriptaccess="samedomain" wmode="Window" allowFullScreen="true"></embed></object>');
}