//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdminText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء التفعيل.
        /// </summary>
        internal static string ActivationCanceled {
            get {
                return ResourceManager.GetString("ActivationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التفعيل.
        /// </summary>
        internal static string ActivationDone {
            get {
                return ResourceManager.GetString("ActivationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة التفعيل.
        /// </summary>
        internal static string ActivationStatus {
            get {
                return ResourceManager.GetString("ActivationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الإضافة بنجاح.
        /// </summary>
        internal static string AddingOperationDone {
            get {
                return ResourceManager.GetString("AddingOperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الإضافة.
        /// </summary>
        internal static string AddingOperationFaild {
            get {
                return ResourceManager.GetString("AddingOperationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        internal static string AdminCPanelTitle {
            get {
                return ResourceManager.GetString("AdminCPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/AdminDesign/Ar/css/admin.css.
        /// </summary>
        internal static string AdminCss {
            get {
                return ResourceManager.GetString("AdminCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفعيل.
        /// </summary>
        internal static string AdminGrid_ActivationStatus {
            get {
                return ResourceManager.GetString("AdminGrid_ActivationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات المفعلة.
        /// </summary>
        internal static string AdminGrid_ActiveComments {
            get {
                return ResourceManager.GetString("AdminGrid_ActiveComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضيف بواسطة.
        /// </summary>
        internal static string AdminGrid_AddedBy {
            get {
                return ResourceManager.GetString("AdminGrid_AddedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاضافة.
        /// </summary>
        internal static string AdminGrid_DateAdded {
            get {
                return ResourceManager.GetString("AdminGrid_DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات غير المفعلة.
        /// </summary>
        internal static string AdminGrid_InActiveComments {
            get {
                return ResourceManager.GetString("AdminGrid_InActiveComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصور.
        /// </summary>
        internal static string AdminGrid_Photos {
            get {
                return ResourceManager.GetString("AdminGrid_Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرد.
        /// </summary>
        internal static string AdminGrid_ReplyStatus {
            get {
                return ResourceManager.GetString("AdminGrid_ReplyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراجعة.
        /// </summary>
        internal static string AdminGrid_ReviewStatus {
            get {
                return ResourceManager.GetString("AdminGrid_ReviewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        internal static string AdminGrid_View {
            get {
                return ResourceManager.GetString("AdminGrid_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية للوحة التحكم بالموقع.
        /// </summary>
        internal static string AdminHomeNote {
            get {
                return ResourceManager.GetString("AdminHomeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/AdminDesign/Ar/css/adminLogin.css.
        /// </summary>
        internal static string AdminLoginCss {
            get {
                return ResourceManager.GetString("AdminLoginCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/AdminDesign/Ar/css/Menu.css.
        /// </summary>
        internal static string AdminMenuCss {
            get {
                return ResourceManager.GetString("AdminMenuCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&apos;direction: rtl;&apos;&gt;
        ///        &lt;center&gt;
        ///            قام مدير الموقع بإنشاء حساب خاص بكم
        ///            &lt;br /&gt;
        ///            &lt;b&gt;بيانات حسابك&lt;/b&gt;
        ///            &lt;br /&gt;
        ///        &lt;/center&gt;
        ///        &lt;b&gt;اسم المستخدم:&lt;/b&gt; {0}
        ///        &lt;br /&gt;
        ///        &lt;b&gt;كلمة المرور:&lt;/b&gt; {1}
        ///    &lt;/div&gt;.
        /// </summary>
        internal static string AdminMessage_NewUserAccountCreationBody {
            get {
                return ResourceManager.GetString("AdminMessage_NewUserAccountCreationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&apos;direction: rtl;&apos;&gt;
        ///        &lt;center&gt;
        ///            قام مدير الموقع بإنشاء حساب خاص بكم
        ///            &lt;br /&gt;
        ///            &lt;b&gt;بيانات حسابك&lt;/b&gt;
        ///            &lt;br /&gt;
        ///        &lt;/center&gt;
        ///       {0}
        ///    &lt;/div&gt;.
        /// </summary>
        internal static string AdminMessage_NewUserAccountCreationBody2 {
            get {
                return ResourceManager.GetString("AdminMessage_NewUserAccountCreationBody2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات حسابك.
        /// </summary>
        internal static string AdminMessage_NewUserAccountCreationSubject {
            get {
                return ResourceManager.GetString("AdminMessage_NewUserAccountCreationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/AdminDesign/Styles/Pager.css.
        /// </summary>
        internal static string AdminPagerCss {
            get {
                return ResourceManager.GetString("AdminPagerCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Align {
            get {
                return ResourceManager.GetString("Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير كلمة المرور.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إختر.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضغط لتكبير الصورة.
        /// </summary>
        internal static string ClickToEnlage {
            get {
                return ResourceManager.GetString("ClickToEnlage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الموقع.
        /// </summary>
        internal static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة.
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة/إنهاء.
        /// </summary>
        internal static string CreateThenFinish {
            get {
                return ResourceManager.GetString("CreateThenFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة/جديد.
        /// </summary>
        internal static string CreateThenNew {
            get {
                return ResourceManager.GetString("CreateThenNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم.
        /// </summary>
        internal static string Date_Day {
            get {
                return ResourceManager.GetString("Date_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to م.
        /// </summary>
        internal static string Date_Georgian {
            get {
                return ResourceManager.GetString("Date_Georgian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الساعة.
        /// </summary>
        internal static string Date_Hour {
            get {
                return ResourceManager.GetString("Date_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هــ.
        /// </summary>
        internal static string Date_Islamic {
            get {
                return ResourceManager.GetString("Date_Islamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدقيقة.
        /// </summary>
        internal static string Date_Minute {
            get {
                return ResourceManager.GetString("Date_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشهر.
        /// </summary>
        internal static string Date_Month {
            get {
                return ResourceManager.GetString("Date_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثانية.
        /// </summary>
        internal static string Date_Second {
            get {
                return ResourceManager.GetString("Date_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة.
        /// </summary>
        internal static string Date_Year {
            get {
                return ResourceManager.GetString("Date_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من إتمام عملية الحذف ؟.
        /// </summary>
        internal static string DeleteActivation {
            get {
                return ResourceManager.GetString("DeleteActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحذف بنجاح.
        /// </summary>
        internal static string DeletingOprationDone {
            get {
                return ResourceManager.GetString("DeletingOprationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الحذف.
        /// </summary>
        internal static string DeletingOprationFaild {
            get {
                return ResourceManager.GetString("DeletingOprationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        internal static string Dir {
            get {
                return ResourceManager.GetString("Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        internal static string DownLoadExistFile {
            get {
                return ResourceManager.GetString("DownLoadExistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل مكرر.
        /// </summary>
        internal static string DuplicateItem {
            get {
                return ResourceManager.GetString("DuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightToLeft.
        /// </summary>
        internal static string EditorDirection {
            get {
                return ResourceManager.GetString("EditorDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير البيانات.
        /// </summary>
        internal static string ExportData {
            get {
                return ResourceManager.GetString("ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/images/Boolean/False.gif.
        /// </summary>
        internal static string FalseImage {
            get {
                return ResourceManager.GetString("FalseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض الخريطة.
        /// </summary>
        internal static string GoogleMapShow {
            get {
                return ResourceManager.GetString("GoogleMapShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ خاطئ.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميل خاطئ.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في القيمة المدخلة.
        /// </summary>
        internal static string InvalidEnteredValue {
            get {
                return ResourceManager.GetString("InvalidEnteredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوجو المرفوع ليس صورة.
        /// </summary>
        internal static string InvalidLogoFile {
            get {
                return ResourceManager.GetString("InvalidLogoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل قيمة رقمية.
        /// </summary>
        internal static string InvalidNumericalData {
            get {
                return ResourceManager.GetString("InvalidNumericalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف المرفوع ليس صورة.
        /// </summary>
        internal static string InvalidPhotoFile {
            get {
                return ResourceManager.GetString("InvalidPhotoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط خاطئ.
        /// </summary>
        internal static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المراجعة.
        /// </summary>
        internal static string IsSeen {
            get {
                return ResourceManager.GetString("IsSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات اللغة العربية.
        /// </summary>
        internal static string LanguageDetails1 {
            get {
                return ResourceManager.GetString("LanguageDetails1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات اللغة الإنجليزية.
        /// </summary>
        internal static string LanguageDetails2 {
            get {
                return ResourceManager.GetString("LanguageDetails2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجي ادخــال معلومات الدخول الخاصة بادارة الموقع.
        /// </summary>
        internal static string LoginBox_Note {
            get {
                return ResourceManager.GetString("LoginBox_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور :.
        /// </summary>
        internal static string LoginBox_Password {
            get {
                return ResourceManager.GetString("LoginBox_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم :.
        /// </summary>
        internal static string LoginBox_UserName {
            get {
                return ResourceManager.GetString("LoginBox_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخر زيارة.
        /// </summary>
        internal static string Login_LastVisit {
            get {
                return ResourceManager.GetString("Login_LastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللوجو.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات.
        /// </summary>
        internal static string ModuleAdmin_AdvModules {
            get {
                return ResourceManager.GetString("ModuleAdmin_AdvModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مجموعة.
        /// </summary>
        internal static string ModuleAdmin_SecurityAddGroup {
            get {
                return ResourceManager.GetString("ModuleAdmin_SecurityAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مستخدم.
        /// </summary>
        internal static string ModuleAdmin_SecurityAddUser {
            get {
                return ResourceManager.GetString("ModuleAdmin_SecurityAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض المجموعات.
        /// </summary>
        internal static string ModuleAdmin_SecurityAllGroups {
            get {
                return ResourceManager.GetString("ModuleAdmin_SecurityAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض المستخدمين.
        /// </summary>
        internal static string ModuleAdmin_SecurityAllUsers {
            get {
                return ResourceManager.GetString("ModuleAdmin_SecurityAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أمن النظام.
        /// </summary>
        internal static string ModuleAdmin_SecurityModule {
            get {
                return ResourceManager.GetString("ModuleAdmin_SecurityModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد لوجو.
        /// </summary>
        internal static string NoLogo {
            get {
                return ResourceManager.GetString("NoLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد صورة.
        /// </summary>
        internal static string NoPhoto {
            get {
                return ResourceManager.GetString("NoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن فقط رفع هذة الإمتدادات لملف الصوت .
        /// </summary>
        internal static string NotSuportedAudioExtention {
            get {
                return ResourceManager.GetString("NotSuportedAudioExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن فقط رفع هذة الإمتدادات للملف .
        /// </summary>
        internal static string NotSuportedFileExtention {
            get {
                return ResourceManager.GetString("NotSuportedFileExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن فقط رفع هذة الإمتدادات لملف الفيديو .
        /// </summary>
        internal static string NotSuportedVideoExtention {
            get {
                return ResourceManager.GetString("NotSuportedVideoExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string OtherLang {
            get {
                return ResourceManager.GetString("OtherLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /AdminCP/LangSpecification.aspx?LangID=2.
        /// </summary>
        internal static string OtherLangLink {
            get {
                return ResourceManager.GetString("OtherLangLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأول.
        /// </summary>
        internal static string PagerFrist {
            get {
                return ResourceManager.GetString("PagerFrist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  من .
        /// </summary>
        internal static string PagerFrom {
            get {
                return ResourceManager.GetString("PagerFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخير.
        /// </summary>
        internal static string PagerLast {
            get {
                return ResourceManager.GetString("PagerLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        internal static string PagerNext {
            get {
                return ResourceManager.GetString("PagerNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  صفحة .
        /// </summary>
        internal static string PagerPageNO {
            get {
                return ResourceManager.GetString("PagerPageNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        internal static string PagerPrevious {
            get {
                return ResourceManager.GetString("PagerPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الحفظ.
        /// </summary>
        internal static string SavingDataFaild {
            get {
                return ResourceManager.GetString("SavingDataFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحفظ.
        /// </summary>
        internal static string SavingDataSuccessfuly {
            get {
                return ResourceManager.GetString("SavingDataSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال إميلات.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الإرسال.
        /// </summary>
        internal static string SendingOperationDone {
            get {
                return ResourceManager.GetString("SendingOperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء عملية الإرسال حاول مرة أخرى.
        /// </summary>
        internal static string SendingOperationFaild {
            get {
                return ResourceManager.GetString("SendingOperationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رسائل قصيرة.
        /// </summary>
        internal static string SendSms {
            get {
                return ResourceManager.GetString("SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string SiteHome {
            get {
                return ResourceManager.GetString("SiteHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئيسية الموقع.
        /// </summary>
        internal static string SiteHomePage {
            get {
                return ResourceManager.GetString("SiteHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى الثابت.
        /// </summary>
        internal static string StaticContents {
            get {
                return ResourceManager.GetString("StaticContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكرأ.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات.
        /// </summary>
        internal static string ThereIsNoData {
            get {
                return ResourceManager.GetString("ThereIsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/images/Boolean/True.gif.
        /// </summary>
        internal static string TrueImage {
            get {
                return ResourceManager.GetString("TrueImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية التعديل.
        /// </summary>
        internal static string UpdatingOperationFaild {
            get {
                return ResourceManager.GetString("UpdatingOperationFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التعديل.
        /// </summary>
        internal static string UpdatingsOperationDone {
            get {
                return ResourceManager.GetString("UpdatingsOperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقصى مساحة مسموحة لملف الصوت .
        /// </summary>
        internal static string UploadedAudioGreaterThanMaxLength {
            get {
                return ResourceManager.GetString("UploadedAudioGreaterThanMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقصى مساحة مسموحة للملف .
        /// </summary>
        internal static string UploadedFileGreaterThanMaxLength {
            get {
                return ResourceManager.GetString("UploadedFileGreaterThanMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقصى مساحة مسموحة لملف الفيديو .
        /// </summary>
        internal static string UploadedVideoGreaterThanMaxLength {
            get {
                return ResourceManager.GetString("UploadedVideoGreaterThanMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحباً بك.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string XAlign {
            get {
                return ResourceManager.GetString("XAlign", resourceCulture);
            }
        }
    }
}
