//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailListAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailListAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MailListAdmin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف مرفق1.
        /// </summary>
        internal static string EmailAttatchFile1 {
            get {
                return ResourceManager.GetString("EmailAttatchFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف مرفق2.
        /// </summary>
        internal static string EmailAttatchFile2 {
            get {
                return ResourceManager.GetString("EmailAttatchFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف مرفق3.
        /// </summary>
        internal static string EmailAttatchFile3 {
            get {
                return ResourceManager.GetString("EmailAttatchFile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسموح فقط بملفات ذات امتداد &quot;pdf  doc  docx  txt  png  jpg  gif &quot;.
        /// </summary>
        internal static string EmailAttatchFileAvialableExtebtions {
            get {
                return ResourceManager.GetString("EmailAttatchFileAvialableExtebtions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        internal static string EMailBody {
            get {
                return ResourceManager.GetString("EMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الرسالة.
        /// </summary>
        internal static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        internal static string Email_Active {
            get {
                return ResourceManager.GetString("Email_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد إلكتروني خاطئ.
        /// </summary>
        internal static string EMail_Invaild {
            get {
                return ResourceManager.GetString("EMail_Invaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإرسال.
        /// </summary>
        internal static string Email_SendingDate {
            get {
                return ResourceManager.GetString("Email_SendingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرسل إلية.
        /// </summary>
        internal static string Email_SendingTo {
            get {
                return ResourceManager.GetString("Email_SendingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد ملف.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا الملف غير صحيح.
        /// </summary>
        internal static string FileNotSupportedFile {
            get {
                return ResourceManager.GetString("FileNotSupportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثال.
        /// </summary>
        internal static string FileSample {
            get {
                return ResourceManager.GetString("FileSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        internal static string ImportMails_File {
            get {
                return ResourceManager.GetString("ImportMails_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح سوى بملف txt.
        /// </summary>
        internal static string ImportMails_FileValidation {
            get {
                return ResourceManager.GetString("ImportMails_FileValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعة.
        /// </summary>
        internal static string ImportMails_GroupName {
            get {
                return ResourceManager.GetString("ImportMails_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملحوظة: الملف لابد ان يكون كل سجل في سطر منفصل بدون أي فواصل بهذا الشكل.
        /// </summary>
        internal static string ImportMails_Note {
            get {
                return ResourceManager.GetString("ImportMails_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة عدد ({0}) بنجاح.
        /// </summary>
        internal static string ImportSuccessfulyCount {
            get {
                return ResourceManager.GetString("ImportSuccessfulyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة البريدية.
        /// </summary>
        internal static string MailListTitle {
            get {
                return ResourceManager.GetString("MailListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        internal static string MailListUsers {
            get {
                return ResourceManager.GetString("MailListUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الإميلات الموجودة بالفعل - {0}.
        /// </summary>
        internal static string NotImportAlradyExistCount {
            get {
                return ResourceManager.GetString("NotImportAlradyExistCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الإميلات التي فشلت عملية إضافتها - {0}.
        /// </summary>
        internal static string NotImportFailiarCount {
            get {
                return ResourceManager.GetString("NotImportFailiarCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الإميلات الخاطئة - {0}.
        /// </summary>
        internal static string NotImportNotMailsCount {
            get {
                return ResourceManager.GetString("NotImportNotMailsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مجموعة.
        /// </summary>
        internal static string Page_AddGroup {
            get {
                return ResourceManager.GetString("Page_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مشترك.
        /// </summary>
        internal static string Page_AddUser {
            get {
                return ResourceManager.GetString("Page_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعات البريدية.
        /// </summary>
        internal static string Page_AllGroups {
            get {
                return ResourceManager.GetString("Page_AllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض المشتركين.
        /// </summary>
        internal static string Page_AllUsers {
            get {
                return ResourceManager.GetString("Page_AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرشيف الرسائل.
        /// </summary>
        internal static string Page_Archive {
            get {
                return ResourceManager.GetString("Page_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير الإميلات.
        /// </summary>
        internal static string Page_ExportToExcellFile {
            get {
                return ResourceManager.GetString("Page_ExportToExcellFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستيراد من إكسل.
        /// </summary>
        internal static string Page_ImportFromExcellFile {
            get {
                return ResourceManager.GetString("Page_ImportFromExcellFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستيراد من ملف.
        /// </summary>
        internal static string Page_ImportFromTxtFile {
            get {
                return ResourceManager.GetString("Page_ImportFromTxtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال للقائمة البريدية.
        /// </summary>
        internal static string Page_SendToAllMailList {
            get {
                return ResourceManager.GetString("Page_SendToAllMailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال لمجموعة.
        /// </summary>
        internal static string Page_SendToGroup {
            get {
                return ResourceManager.GetString("Page_SendToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال لأكثر من مجموعة.
        /// </summary>
        internal static string Page_SendToMultiGroup {
            get {
                return ResourceManager.GetString("Page_SendToMultiGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال لاكثر من بريد في مجموعة.
        /// </summary>
        internal static string Page_SendToMultiUsersInGroup {
            get {
                return ResourceManager.GetString("Page_SendToMultiUsersInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال لمستخدم.
        /// </summary>
        internal static string Page_SendToUser {
            get {
                return ResourceManager.GetString("Page_SendToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لابد من إختيار مجموعة واحدة على الأقل.
        /// </summary>
        internal static string Result_ChoesOneGroupAtLeast {
            get {
                return ResourceManager.GetString("Result_ChoesOneGroupAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لابد من إختيار مشترك واحد على الأقل.
        /// </summary>
        internal static string Result_ChoesOneUserAtLeast {
            get {
                return ResourceManager.GetString("Result_ChoesOneUserAtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد إلكتروني خاطئ.
        /// </summary>
        internal static string Result_InvalidMail {
            get {
                return ResourceManager.GetString("Result_InvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الارسال بنجاح.
        /// </summary>
        internal static string Result_SendingDone {
            get {
                return ResourceManager.GetString("Result_SendingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث بالبريد الإلكتروني.
        /// </summary>
        internal static string SearchByEmail {
            get {
                return ResourceManager.GetString("SearchByEmail", resourceCulture);
            }
        }
    }
}
