//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmsAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmsAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SmsAdmin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف كل رسائل الأرشيف.
        /// </summary>
        internal static string Archive_DeleteAllData {
            get {
                return ResourceManager.GetString("Archive_DeleteAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد الحالى.
        /// </summary>
        internal static string CurrentBalance {
            get {
                return ResourceManager.GetString("CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد ملف.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا الملف غير صحيح.
        /// </summary>
        internal static string FileNotSupportedFile {
            get {
                return ResourceManager.GetString("FileNotSupportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثال.
        /// </summary>
        internal static string FileSample {
            get {
                return ResourceManager.GetString("FileSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المجموعة.
        /// </summary>
        internal static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملحوظة: الملف لابد ان يكون كل سجل في سطر منفصل بدون أي فواصل بهذا الشكل.
        /// </summary>
        internal static string ImportNumbers_Note {
            get {
                return ResourceManager.GetString("ImportNumbers_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح سوى بملف إكسل.
        /// </summary>
        internal static string ImportSms_ExcellFileValidation {
            get {
                return ResourceManager.GetString("ImportSms_ExcellFileValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        internal static string ImportSms_File {
            get {
                return ResourceManager.GetString("ImportSms_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح سوى بملف txt.
        /// </summary>
        internal static string ImportSms_FileValidation {
            get {
                return ResourceManager.GetString("ImportSms_FileValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة عدد ({0}) بنجاح.
        /// </summary>
        internal static string ImportSuccessfulyCount {
            get {
                return ResourceManager.GetString("ImportSuccessfulyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم.
        /// </summary>
        internal static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        internal static string Mobile_Active {
            get {
                return ResourceManager.GetString("Mobile_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        internal static string MsgBody {
            get {
                return ResourceManager.GetString("MsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأرقام الموجودة بالفعل - {0}.
        /// </summary>
        internal static string NotImportAlradyExistCount {
            get {
                return ResourceManager.GetString("NotImportAlradyExistCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأرقام التي فشلت عملية إضافتها - {0}.
        /// </summary>
        internal static string NotImportFailiarCount {
            get {
                return ResourceManager.GetString("NotImportFailiarCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأرقام الخاطئة - {0}.
        /// </summary>
        internal static string NotImportNotNumbersCount {
            get {
                return ResourceManager.GetString("NotImportNotNumbersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مجموعة.
        /// </summary>
        internal static string Page_AddGroup {
            get {
                return ResourceManager.GetString("Page_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مشترك.
        /// </summary>
        internal static string Page_AddUser {
            get {
                return ResourceManager.GetString("Page_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعات البريدية.
        /// </summary>
        internal static string Page_AllGroups {
            get {
                return ResourceManager.GetString("Page_AllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض المشتركين.
        /// </summary>
        internal static string Page_AllUsers {
            get {
                return ResourceManager.GetString("Page_AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرشيف الرسائل.
        /// </summary>
        internal static string Page_Archive {
            get {
                return ResourceManager.GetString("Page_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستيراد من إكسل.
        /// </summary>
        internal static string Page_ImportFromExcellFile {
            get {
                return ResourceManager.GetString("Page_ImportFromExcellFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستيراد من ملف.
        /// </summary>
        internal static string Page_ImportFromTxtFile {
            get {
                return ResourceManager.GetString("Page_ImportFromTxtFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال للقائمة البريدية.
        /// </summary>
        internal static string Page_SendToAllSmsList {
            get {
                return ResourceManager.GetString("Page_SendToAllSmsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال لمجموعة.
        /// </summary>
        internal static string Page_SendToGroup {
            get {
                return ResourceManager.GetString("Page_SendToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال لمستخدم.
        /// </summary>
        internal static string Page_SendToUser {
            get {
                return ResourceManager.GetString("Page_SendToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى الرقم.
        /// </summary>
        internal static string Result_ErrorInNumber {
            get {
                return ResourceManager.GetString("Result_ErrorInNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الارسال بنجاح.
        /// </summary>
        internal static string Result_SendingDone {
            get {
                return ResourceManager.GetString("Result_SendingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مركز رسائل الجوال.
        /// </summary>
        internal static string SmsModuleTitle {
            get {
                return ResourceManager.GetString("SmsModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرقام الجوال بمفاتيح الدول دون اصفار.
        /// </summary>
        internal static string SmsNoteAddingNumbers {
            get {
                return ResourceManager.GetString("SmsNoteAddingNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرسل إليه.
        /// </summary>
        internal static string SmsReciever {
            get {
                return ResourceManager.GetString("SmsReciever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الراسل.
        /// </summary>
        internal static string SmsSender {
            get {
                return ResourceManager.GetString("SmsSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل.
        /// </summary>
        internal static string Sms_Active {
            get {
                return ResourceManager.GetString("Sms_Active", resourceCulture);
            }
        }
    }
}
