//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Zecurity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Zecurity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Zecurity", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة قسم.
        /// </summary>
        internal static string AddDeparment {
            get {
                return ResourceManager.GetString("AddDeparment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجابة السؤال السري.
        /// </summary>
        internal static string AnswerLabelText {
            get {
                return ResourceManager.GetString("AnswerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل السؤال السري.
        /// </summary>
        internal static string AnswerRequiredErrorMessage {
            get {
                return ResourceManager.GetString("AnswerRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم االإضافة بنجاح.
        /// </summary>
        internal static string CompleteSuccessText {
            get {
                return ResourceManager.GetString("CompleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة.
        /// </summary>
        internal static string ConfirmPasswordCompareErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordCompareErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        internal static string ConfirmPasswordLabelText {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل تأكيد كلمة المرور.
        /// </summary>
        internal static string ConfirmPasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستمرار.
        /// </summary>
        internal static string ContinueButtonText {
            get {
                return ResourceManager.GetString("ContinueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string CreateUserButtonText {
            get {
                return ResourceManager.GetString("CreateUserButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        internal static string Deparment {
            get {
                return ResourceManager.GetString("Deparment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأقسام.
        /// </summary>
        internal static string Deparments {
            get {
                return ResourceManager.GetString("Deparments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني مسجل لدينا لحساب أخر.
        /// </summary>
        internal static string DuplicateEmailErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم موجود لحساب أخر.
        /// </summary>
        internal static string DuplicateUserNameErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateUserNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string EmailLabelText {
            get {
                return ResourceManager.GetString("EmailLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد إلكتروني خاطئ.
        /// </summary>
        internal static string EmailRegularExpressionErrorMessage {
            get {
                return ResourceManager.GetString("EmailRegularExpressionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل البريد الإلكتروني.
        /// </summary>
        internal static string EmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("EmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنهاء.
        /// </summary>
        internal static string FinishCompleteButtonText {
            get {
                return ResourceManager.GetString("FinishCompleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عودة.
        /// </summary>
        internal static string FinishPreviousButtonText {
            get {
                return ResourceManager.GetString("FinishPreviousButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعات.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل إجابة أخرى.
        /// </summary>
        internal static string InvalidAnswerErrorMessage {
            get {
                return ResourceManager.GetString("InvalidAnswerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد خاطئ.
        /// </summary>
        internal static string InvalidEmailErrorMessage {
            get {
                return ResourceManager.GetString("InvalidEmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور لابد أن تكون أكبر من {0} كلمة.
        /// </summary>
        internal static string InvalidPasswordErrorMessage {
            get {
                return ResourceManager.GetString("InvalidPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال السري خاطئ.
        /// </summary>
        internal static string InvalidQuestionErrorMessage {
            get {
                return ResourceManager.GetString("InvalidQuestionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string PasswordLabelText {
            get {
                return ResourceManager.GetString("PasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور لابد أن تكون أكبر من {0} كلمة.
        /// </summary>
        internal static string PasswordRegularExpressionErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRegularExpressionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل كلمة المرور.
        /// </summary>
        internal static string PasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("PasswordRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسار.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما هو لونك المفضل؟.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال السري.
        /// </summary>
        internal static string QuestionLabelText {
            get {
                return ResourceManager.GetString("QuestionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل السؤال السري.
        /// </summary>
        internal static string QuestionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("QuestionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أضف الصلاحيات والموديولات أولاً.
        /// </summary>
        internal static string Result_AddPermissionsAndModule {
            get {
                return ResourceManager.GetString("Result_AddPermissionsAndModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الإضافة لا يمكن تكرار اسم مجموعة.
        /// </summary>
        internal static string Result_GroupNameDuplicated {
            get {
                return ResourceManager.GetString("Result_GroupNameDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        internal static string StartNextButtonText {
            get {
                return ResourceManager.GetString("StartNextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        internal static string StepNextButtonText {
            get {
                return ResourceManager.GetString("StepNextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابق.
        /// </summary>
        internal static string StepPreviousButtonText {
            get {
                return ResourceManager.GetString("StepPreviousButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في الإضافة حاول مرة أخرى في وقت أخر.
        /// </summary>
        internal static string UnknownErrorMessage {
            get {
                return ResourceManager.GetString("UnknownErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        internal static string UserNameLabelText {
            get {
                return ResourceManager.GetString("UserNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل اسم المستخدم.
        /// </summary>
        internal static string UserNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أمن النظام.
        /// </summary>
        internal static string ZecurityModuleTitle {
            get {
                return ResourceManager.GetString("ZecurityModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        internal static string ZecurityUserAccountActive {
            get {
                return ResourceManager.GetString("ZecurityUserAccountActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الأساسية.
        /// </summary>
        internal static string ZecurityUserBasicData {
            get {
                return ResourceManager.GetString("ZecurityUserBasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المستخدم.
        /// </summary>
        internal static string ZecurityUserData {
            get {
                return ResourceManager.GetString("ZecurityUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإضافة.
        /// </summary>
        internal static string ZecurityUserDateAdded {
            get {
                return ResourceManager.GetString("ZecurityUserDateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متواجد.
        /// </summary>
        internal static string ZecurityUserExist {
            get {
                return ResourceManager.GetString("ZecurityUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخر دخول.
        /// </summary>
        internal static string ZecurityUserLastLogin {
            get {
                return ResourceManager.GetString("ZecurityUserLastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        internal static string ZecurityUsers {
            get {
                return ResourceManager.GetString("ZecurityUsers", resourceCulture);
            }
        }
    }
}
