//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Advertisments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Advertisments() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Advertisments", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jpg,.gif,.swf.
        /// </summary>
        internal static string AdFileAvailableExtension {
            get {
                return ResourceManager.GetString("AdFileAvailableExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات.
        /// </summary>
        internal static string AdvertismentsModuleTitle {
            get {
                return ResourceManager.GetString("AdvertismentsModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلان.
        /// </summary>
        internal static string AdvItem {
            get {
                return ResourceManager.GetString("AdvItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسار الملف الإفتراضي.
        /// </summary>
        internal static string AdvPlaces_DefaultFilePath {
            get {
                return ResourceManager.GetString("AdvPlaces_DefaultFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الملف الإفتراضي.
        /// </summary>
        internal static string AdvPlaces_DefaultFileType {
            get {
                return ResourceManager.GetString("AdvPlaces_DefaultFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد التقسيمات.
        /// </summary>
        internal static string AdvPlaces_EnableSeparatedCount {
            get {
                return ResourceManager.GetString("AdvPlaces_EnableSeparatedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطول.
        /// </summary>
        internal static string AdvPlaces_Height {
            get {
                return ResourceManager.GetString("AdvPlaces_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض عشوائي.
        /// </summary>
        internal static string AdvPlaces_IsRandom {
            get {
                return ResourceManager.GetString("AdvPlaces_IsRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        internal static string AdvPlaces_PlaceID {
            get {
                return ResourceManager.GetString("AdvPlaces_PlaceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعرف.
        /// </summary>
        internal static string AdvPlaces_PlaceIdentifier {
            get {
                return ResourceManager.GetString("AdvPlaces_PlaceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المساحة الإعلانية.
        /// </summary>
        internal static string AdvPlaces_PlaceType {
            get {
                return ResourceManager.GetString("AdvPlaces_PlaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكان.
        /// </summary>
        internal static string AdvPlaces_Title {
            get {
                return ResourceManager.GetString("AdvPlaces_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العرض.
        /// </summary>
        internal static string AdvPlaces_Width {
            get {
                return ResourceManager.GetString("AdvPlaces_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السماح بتقصيم الإعلان.
        /// </summary>
        internal static string Adv_EnableSeparatedAd {
            get {
                return ResourceManager.GetString("Adv_EnableSeparatedAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد مرات ظهور الإعلان.
        /// </summary>
        internal static string ApperanceCount {
            get {
                return ResourceManager.GetString("ApperanceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد مرات الضغط على الإعلان.
        /// </summary>
        internal static string ClicksCount {
            get {
                return ResourceManager.GetString("ClicksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableSeparatedCount {
            get {
                return ResourceManager.GetString("EnableSeparatedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        internal static string FileExtension {
            get {
                return ResourceManager.GetString("FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string FileMaxSize {
            get {
                return ResourceManager.GetString("FileMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الملف.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة التفعيل.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعلان صغير.
        /// </summary>
        internal static string IsSmall {
            get {
                return ResourceManager.GetString("IsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقصى عدد لمرات الظهور.
        /// </summary>
        internal static string MaxApperance {
            get {
                return ResourceManager.GetString("MaxApperance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقصى عدد للضغط على الإعلان.
        /// </summary>
        internal static string MaxClicks {
            get {
                return ResourceManager.GetString("MaxClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الإعلان.
        /// </summary>
        internal static string PlaceID {
            get {
                return ResourceManager.GetString("PlaceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرص الظهور.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
