//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalTexts", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مادة.
        /// </summary>
        internal static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كاتب.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كتاب.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملف.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محاضر.
        /// </summary>
        internal static string LectureProf {
            get {
                return ResourceManager.GetString("LectureProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إستماع.
        /// </summary>
        internal static string Listen {
            get {
                return ResourceManager.GetString("Listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة.
        /// </summary>
        internal static string TheAudio {
            get {
                return ResourceManager.GetString("TheAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكاتب.
        /// </summary>
        internal static string TheAuthor {
            get {
                return ResourceManager.GetString("TheAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكتاب.
        /// </summary>
        internal static string TheBook {
            get {
                return ResourceManager.GetString("TheBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        internal static string TheFile {
            get {
                return ResourceManager.GetString("TheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحاضر.
        /// </summary>
        internal static string TheLectureProf {
            get {
                return ResourceManager.GetString("TheLectureProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة.
        /// </summary>
        internal static string TheVideo {
            get {
                return ResourceManager.GetString("TheVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مادة.
        /// </summary>
        internal static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهدة.
        /// </summary>
        internal static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
    }
}
