//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MailList", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا البريد مفعل بالفعل.
        /// </summary>
        internal static string ActivationAlredyDone {
            get {
                return ResourceManager.GetString("ActivationAlredyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل اشتراكك في القائمة البريدية.
        /// </summary>
        internal static string ActivationDone {
            get {
                return ResourceManager.GetString("ActivationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية تفعيل إشتراكك في القائمة البريدية من فضلك حاول في وقت أخر.
        /// </summary>
        internal static string ActivationFailed {
            get {
                return ResourceManager.GetString("ActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;center&gt;نشكركم علي التسجيل في القائمة البريدية للموقع&lt;/center&gt;&lt;br /&gt;&lt;center&gt;لتفعيل الإشتراك &lt;a target=_blank href=&apos;{0}website/MailList/Activate.aspx?ID={1}&amp;Email={2}&apos;&gt;اضغط هنا ,&lt;/a&gt;&lt;center&gt;.
        /// </summary>
        internal static string ActivationMailBody {
            get {
                return ResourceManager.GetString("ActivationMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشكركم علي التسجيل في القائمة البريدية للموقع.
        /// </summary>
        internal static string ActivationMailSubject {
            get {
                return ResourceManager.GetString("ActivationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد مسجل من قبل.
        /// </summary>
        internal static string ExistsEmail {
            get {
                return ResourceManager.GetString("ExistsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعة.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد إلكتروني خاطئ.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات خاطئة.
        /// </summary>
        internal static string InvalidParameters {
            get {
                return ResourceManager.GetString("InvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة البريدية.
        /// </summary>
        internal static string MailListTitle {
            get {
                return ResourceManager.GetString("MailListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة البريدية.
        /// </summary>
        internal static string SubscripeBoxTitle {
            get {
                return ResourceManager.GetString("SubscripeBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /App_Design/User/Design/Ar/Images/Buttons/Send.gif.
        /// </summary>
        internal static string SubscripeBtnImageUrl {
            get {
                return ResourceManager.GetString("SubscripeBtnImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إشترك.
        /// </summary>
        internal static string SubscripeBtnText {
            get {
                return ResourceManager.GetString("SubscripeBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الاضافة للقائمة البريدية.
        /// </summary>
        internal static string SubscripeDone {
            get {
                return ResourceManager.GetString("SubscripeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية الإشتراك.
        /// </summary>
        internal static string SubscripeFailed {
            get {
                return ResourceManager.GetString("SubscripeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا البريد غير موجود في قائمتنا البريدية.
        /// </summary>
        internal static string ThisMailisnotSubcribeToOurMaillist {
            get {
                return ResourceManager.GetString("ThisMailisnotSubcribeToOurMaillist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء إشتراكك في القائمة البريدية.
        /// </summary>
        internal static string UnSubscripeDone {
            get {
                return ResourceManager.GetString("UnSubscripeDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشلت عملية إلغاء إشتراكك في القائمة البريدية من فضلك حاول في وقت أخر.
        /// </summary>
        internal static string UnSubscripeFailed {
            get {
                return ResourceManager.GetString("UnSubscripeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;br /&gt;&lt;center&gt; لإلغاء الإشتراك في القائمة البريدية &lt;a target=_blank href=&apos;{0}website/MailList/Unsubscripe.aspx?ID={1}&amp;Email={2}&apos;&gt; اضغط هنا &lt;/a&gt;&lt;center&gt;.
        /// </summary>
        internal static string UnsubscripeLink {
            get {
                return ResourceManager.GetString("UnsubscripeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;br /&gt;&lt;center&gt; لإلغاء الإشتراك في القائمة البريدية &lt;a target=_blank href=&apos;{0}website/MailList/Unsubscripe.aspx?ID={1}&amp;Email={2}&apos;&gt; اضغط هنا &lt;/a&gt;&lt;center&gt;.
        /// </summary>
        internal static string WelcomeMessageBody {
            get {
                return ResourceManager.GetString("WelcomeMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا في القائمة البريدية.
        /// </summary>
        internal static string WelcomeMessageSubject {
            get {
                return ResourceManager.GetString("WelcomeMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لابد من إختيار تصنيف واحد على الأقل .
        /// </summary>
        internal static string YouMustChooseOneGroupAtLeast {
            get {
                return ResourceManager.GetString("YouMustChooseOneGroupAtLeast", resourceCulture);
            }
        }
    }
}
