//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Modules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Modules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Modules", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_About_Us {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Advertisments {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Advertisments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقالات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Articles {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتبة المسموعة.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Audios {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Audios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكتاب.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Authors {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدونة.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Blog {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجز فحص طبي.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Booking {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتبة المقرؤة.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Books {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المطاعم.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Branches {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفعاليات والأحداث.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Calendar {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظائف.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Career {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوظيف.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_CareerRequest {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_CareerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملاؤنا.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Clients {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشاريين.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Consultants {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Consultants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشارات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Consulting_Services {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Consulting_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتصل بنا.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Contact_Us {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابات الأطباء.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Doctors {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاعليات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Events {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعاون معنا .
        /// </summary>
        internal static string ModuleAdminSpecialTitle_FaceContact_Us {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_FaceContact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موديول فرحات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Fara7ota {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Fara7ota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواقع مهمة.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Friendly_Sites {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Friendly_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هيدر الموقع.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Header {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة البريدية.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_MailList {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_MailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعضاء المنتدى  .
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Mem {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوال تفسير.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Mobile_Messages {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Mobile_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابطة المتخصصين.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Motakhasesen {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Motakhasesen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد الاصدارات القرأنية.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_NewReleases {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_NewReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحداث.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_News {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عروض خاصة.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Offers {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركاؤنا فيس.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Partners {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفعاليات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_PhotoGallery {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_PhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقة الأعمال.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Portfolio {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Products {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشروعات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Projects {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصداراتنا.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Publications {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Publications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في الموقع  .
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Registration {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشاريين.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Registration_Consultant {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Registration_Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في الموقع.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Registration_User {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Registration_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدماتنا.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Services {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى الثابت.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_SitePages {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_SitePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوكلاء.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_SiteUsers {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_SiteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوال الموقع.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_SMS {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحلول.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Solutions {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعضاء الموقع.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_SubAdmins {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_SubAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Subscribtion {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Subscribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحات المواقع الفرعية.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_SubSitePages {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_SubSitePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفريق الطبي.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_TeamWork {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_TeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملفات .
        /// </summary>
        internal static string ModuleAdminSpecialTitle_UsersFiles {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_UsersFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ألبوم الصور.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_UsersPhotos {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_UsersPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعريف بالأعضاء.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_UsersProfiles {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_UsersProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  جديد المناشط.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_UsersSites {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_UsersSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفيديوهات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_UsersVideos {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_UsersVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقالات.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Users_Articles {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Users_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صور الهيدر.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Users_HeaderPhotos {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Users_HeaderPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخبار.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Users_News {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Users_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتبة المرئية.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Vedios {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Vedios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع الزوار.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_VisitorSigns {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_VisitorSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستبيان.
        /// </summary>
        internal static string ModuleAdminSpecialTitle_Vote {
            get {
                return ResourceManager.GetString("ModuleAdminSpecialTitle_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        internal static string ModuleTitle_About_Us {
            get {
                return ResourceManager.GetString("ModuleTitle_About_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلانات.
        /// </summary>
        internal static string ModuleTitle_Advertisments {
            get {
                return ResourceManager.GetString("ModuleTitle_Advertisments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقالات.
        /// </summary>
        internal static string ModuleTitle_Articles {
            get {
                return ResourceManager.GetString("ModuleTitle_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتبة المسموعة.
        /// </summary>
        internal static string ModuleTitle_Audios {
            get {
                return ResourceManager.GetString("ModuleTitle_Audios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكتاب.
        /// </summary>
        internal static string ModuleTitle_Authors {
            get {
                return ResourceManager.GetString("ModuleTitle_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدونة.
        /// </summary>
        internal static string ModuleTitle_Blog {
            get {
                return ResourceManager.GetString("ModuleTitle_Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجز فحص طبي.
        /// </summary>
        internal static string ModuleTitle_Booking {
            get {
                return ResourceManager.GetString("ModuleTitle_Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتبة المقرؤة.
        /// </summary>
        internal static string ModuleTitle_Books {
            get {
                return ResourceManager.GetString("ModuleTitle_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المطاعم.
        /// </summary>
        internal static string ModuleTitle_Branches {
            get {
                return ResourceManager.GetString("ModuleTitle_Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفعاليات والأحداث.
        /// </summary>
        internal static string ModuleTitle_Calendar {
            get {
                return ResourceManager.GetString("ModuleTitle_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظائف.
        /// </summary>
        internal static string ModuleTitle_Career {
            get {
                return ResourceManager.GetString("ModuleTitle_Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوظيف.
        /// </summary>
        internal static string ModuleTitle_CareerRequest {
            get {
                return ResourceManager.GetString("ModuleTitle_CareerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملاؤنا.
        /// </summary>
        internal static string ModuleTitle_Clients {
            get {
                return ResourceManager.GetString("ModuleTitle_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشاريين.
        /// </summary>
        internal static string ModuleTitle_Consultants {
            get {
                return ResourceManager.GetString("ModuleTitle_Consultants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشارات.
        /// </summary>
        internal static string ModuleTitle_Consulting_Services {
            get {
                return ResourceManager.GetString("ModuleTitle_Consulting_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتصل بنا.
        /// </summary>
        internal static string ModuleTitle_Contact_Us {
            get {
                return ResourceManager.GetString("ModuleTitle_Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابات الأطباء.
        /// </summary>
        internal static string ModuleTitle_Doctors {
            get {
                return ResourceManager.GetString("ModuleTitle_Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاعليات.
        /// </summary>
        internal static string ModuleTitle_Events {
            get {
                return ResourceManager.GetString("ModuleTitle_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعاون معنا .
        /// </summary>
        internal static string ModuleTitle_FaceContact_Us {
            get {
                return ResourceManager.GetString("ModuleTitle_FaceContact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موديول فرحات.
        /// </summary>
        internal static string ModuleTitle_Fara7ota {
            get {
                return ResourceManager.GetString("ModuleTitle_Fara7ota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواقع مهمة.
        /// </summary>
        internal static string ModuleTitle_Friendly_Sites {
            get {
                return ResourceManager.GetString("ModuleTitle_Friendly_Sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هيدر الموقع.
        /// </summary>
        internal static string ModuleTitle_Header {
            get {
                return ResourceManager.GetString("ModuleTitle_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة البريدية.
        /// </summary>
        internal static string ModuleTitle_MailList {
            get {
                return ResourceManager.GetString("ModuleTitle_MailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعضاء الموقع.
        /// </summary>
        internal static string ModuleTitle_Mem {
            get {
                return ResourceManager.GetString("ModuleTitle_Mem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوال تفسير.
        /// </summary>
        internal static string ModuleTitle_Mobile_Messages {
            get {
                return ResourceManager.GetString("ModuleTitle_Mobile_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابطة المتخصصين.
        /// </summary>
        internal static string ModuleTitle_Motakhasesen {
            get {
                return ResourceManager.GetString("ModuleTitle_Motakhasesen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد الاصدارات القرأنية.
        /// </summary>
        internal static string ModuleTitle_NewReleases {
            get {
                return ResourceManager.GetString("ModuleTitle_NewReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحداث.
        /// </summary>
        internal static string ModuleTitle_News {
            get {
                return ResourceManager.GetString("ModuleTitle_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عروض خاصة.
        /// </summary>
        internal static string ModuleTitle_Offers {
            get {
                return ResourceManager.GetString("ModuleTitle_Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركاؤنا فيس.
        /// </summary>
        internal static string ModuleTitle_Partners {
            get {
                return ResourceManager.GetString("ModuleTitle_Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفعاليات.
        /// </summary>
        internal static string ModuleTitle_PhotoGallery {
            get {
                return ResourceManager.GetString("ModuleTitle_PhotoGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقة الأعمال.
        /// </summary>
        internal static string ModuleTitle_Portfolio {
            get {
                return ResourceManager.GetString("ModuleTitle_Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القائمة.
        /// </summary>
        internal static string ModuleTitle_Products {
            get {
                return ResourceManager.GetString("ModuleTitle_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشروعات.
        /// </summary>
        internal static string ModuleTitle_Projects {
            get {
                return ResourceManager.GetString("ModuleTitle_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اصداراتنا.
        /// </summary>
        internal static string ModuleTitle_Publications {
            get {
                return ResourceManager.GetString("ModuleTitle_Publications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في الموقع  .
        /// </summary>
        internal static string ModuleTitle_Registration {
            get {
                return ResourceManager.GetString("ModuleTitle_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستشاريين.
        /// </summary>
        internal static string ModuleTitle_Registration_Consultant {
            get {
                return ResourceManager.GetString("ModuleTitle_Registration_Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل في الموقع.
        /// </summary>
        internal static string ModuleTitle_Registration_User {
            get {
                return ResourceManager.GetString("ModuleTitle_Registration_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدماتنا.
        /// </summary>
        internal static string ModuleTitle_Services {
            get {
                return ResourceManager.GetString("ModuleTitle_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحتوى الثابت.
        /// </summary>
        internal static string ModuleTitle_SitePages {
            get {
                return ResourceManager.GetString("ModuleTitle_SitePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوكلاء.
        /// </summary>
        internal static string ModuleTitle_SiteUsers {
            get {
                return ResourceManager.GetString("ModuleTitle_SiteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوال الموقع.
        /// </summary>
        internal static string ModuleTitle_SMS {
            get {
                return ResourceManager.GetString("ModuleTitle_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحلول.
        /// </summary>
        internal static string ModuleTitle_Solutions {
            get {
                return ResourceManager.GetString("ModuleTitle_Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعضاء الرابطة.
        /// </summary>
        internal static string ModuleTitle_SubAdmins {
            get {
                return ResourceManager.GetString("ModuleTitle_SubAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        internal static string ModuleTitle_Subscribtion {
            get {
                return ResourceManager.GetString("ModuleTitle_Subscribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModuleTitle_SubSitePages {
            get {
                return ResourceManager.GetString("ModuleTitle_SubSitePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفريق الطبي.
        /// </summary>
        internal static string ModuleTitle_TeamWork {
            get {
                return ResourceManager.GetString("ModuleTitle_TeamWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملفات.
        /// </summary>
        internal static string ModuleTitle_UsersFiles {
            get {
                return ResourceManager.GetString("ModuleTitle_UsersFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرض الصور.
        /// </summary>
        internal static string ModuleTitle_UsersPhotos {
            get {
                return ResourceManager.GetString("ModuleTitle_UsersPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعريف بالأعضاء.
        /// </summary>
        internal static string ModuleTitle_UsersProfiles {
            get {
                return ResourceManager.GetString("ModuleTitle_UsersProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواقع صديقة.
        /// </summary>
        internal static string ModuleTitle_UsersSites {
            get {
                return ResourceManager.GetString("ModuleTitle_UsersSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفيديوهات.
        /// </summary>
        internal static string ModuleTitle_UsersVideos {
            get {
                return ResourceManager.GetString("ModuleTitle_UsersVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقالات.
        /// </summary>
        internal static string ModuleTitle_Users_Articles {
            get {
                return ResourceManager.GetString("ModuleTitle_Users_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صور الهيدر.
        /// </summary>
        internal static string ModuleTitle_Users_HeaderPhotos {
            get {
                return ResourceManager.GetString("ModuleTitle_Users_HeaderPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخبار.
        /// </summary>
        internal static string ModuleTitle_Users_News {
            get {
                return ResourceManager.GetString("ModuleTitle_Users_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتبة المرئية.
        /// </summary>
        internal static string ModuleTitle_Vedios {
            get {
                return ResourceManager.GetString("ModuleTitle_Vedios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توقيع الزوار.
        /// </summary>
        internal static string ModuleTitle_VisitorSigns {
            get {
                return ResourceManager.GetString("ModuleTitle_VisitorSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستبيان.
        /// </summary>
        internal static string ModuleTitle_Vote {
            get {
                return ResourceManager.GetString("ModuleTitle_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الرسائل.
        /// </summary>
        internal static string Module_AllMessage {
            get {
                return ResourceManager.GetString("Module_AllMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقالات.
        /// </summary>
        internal static string Module_Articles {
            get {
                return ResourceManager.GetString("Module_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة تصنيف.
        /// </summary>
        internal static string Module_CategoriesAdd {
            get {
                return ResourceManager.GetString("Module_CategoriesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيفات.
        /// </summary>
        internal static string Module_CategoriesDefault {
            get {
                return ResourceManager.GetString("Module_CategoriesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل تصنيف.
        /// </summary>
        internal static string Module_CategoriesEdit {
            get {
                return ResourceManager.GetString("Module_CategoriesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        internal static string Module_Comments {
            get {
                return ResourceManager.GetString("Module_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات المفعلة.
        /// </summary>
        internal static string Module_CommentsActive {
            get {
                return ResourceManager.GetString("Module_CommentsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات غير المفعلة.
        /// </summary>
        internal static string Module_CommentsInactive {
            get {
                return ResourceManager.GetString("Module_CommentsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير البيانات.
        /// </summary>
        internal static string Module_ExportData {
            get {
                return ResourceManager.GetString("Module_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string Module_ItemsAdd {
            get {
                return ResourceManager.GetString("Module_ItemsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        internal static string Module_ItemsDefault {
            get {
                return ResourceManager.GetString("Module_ItemsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Module_ItemsEdit {
            get {
                return ResourceManager.GetString("Module_ItemsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصور.
        /// </summary>
        internal static string Module_ItemsPhotos {
            get {
                return ResourceManager.GetString("Module_ItemsPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة صورة.
        /// </summary>
        internal static string Module_ItemsPhotosAdd {
            get {
                return ResourceManager.GetString("Module_ItemsPhotosAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الرسالة.
        /// </summary>
        internal static string Module_MessageData {
            get {
                return ResourceManager.GetString("Module_MessageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد الرسائل.
        /// </summary>
        internal static string Module_NewMessage {
            get {
                return ResourceManager.GetString("Module_NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بياناتي.
        /// </summary>
        internal static string MyProfileData {
            get {
                return ResourceManager.GetString("MyProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواقع الأعضاء.
        /// </summary>
        internal static string PageTitle_RabetaMembersSites {
            get {
                return ResourceManager.GetString("PageTitle_RabetaMembersSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحث.
        /// </summary>
        internal static string PageTitle_Search {
            get {
                return ResourceManager.GetString("PageTitle_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خريطة الموقع.
        /// </summary>
        internal static string PageTitle_SiteMap {
            get {
                return ResourceManager.GetString("PageTitle_SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من أنا.
        /// </summary>
        internal static string PageTitle_UserProfilePage {
            get {
                return ResourceManager.GetString("PageTitle_UserProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال إميلات.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رسائل قصيرة.
        /// </summary>
        internal static string SendSms {
            get {
                return ResourceManager.GetString("SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string _Home {
            get {
                return ResourceManager.GetString("_Home", resourceCulture);
            }
        }
    }
}
