//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عن السكينة.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الخدمات.
        /// </summary>
        internal static string AllServices {
            get {
                return ResourceManager.GetString("AllServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدونة.
        /// </summary>
        internal static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اراء عملائنا.
        /// </summary>
        internal static string ClientsVoice {
            get {
                return ResourceManager.GetString("ClientsVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        internal static string ContactFormEmail {
            get {
                return ResourceManager.GetString("ContactFormEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اترك رسالتك.
        /// </summary>
        internal static string ContactFormLeaveYourMessage {
            get {
                return ResourceManager.GetString("ContactFormLeaveYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        internal static string ContactFormMessage {
            get {
                return ResourceManager.GetString("ContactFormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string ContactFormName {
            get {
                return ResourceManager.GetString("ContactFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        internal static string ContactFormSend {
            get {
                return ResourceManager.GetString("ContactFormSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استلام رسالتك شكراً جزيلا لتوصلك معنا.
        /// </summary>
        internal static string ContactFormSuccessSent {
            get {
                return ResourceManager.GetString("ContactFormSuccessSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان:.
        /// </summary>
        internal static string ContactsAddress {
            get {
                return ResourceManager.GetString("ContactsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الاتصال.
        /// </summary>
        internal static string ContactsData {
            get {
                return ResourceManager.GetString("ContactsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد:.
        /// </summary>
        internal static string ContactsEmail {
            get {
                return ResourceManager.GetString("ContactsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاكس:.
        /// </summary>
        internal static string ContactsFax {
            get {
                return ResourceManager.GetString("ContactsFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تواصل معنا.
        /// </summary>
        internal static string ContactsFormCaption {
            get {
                return ResourceManager.GetString("ContactsFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التليفون:.
        /// </summary>
        internal static string ContactsTel {
            get {
                return ResourceManager.GetString("ContactsTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتب.
        /// </summary>
        internal static string ContactsTheOffice {
            get {
                return ResourceManager.GetString("ContactsTheOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إتصل بنا.
        /// </summary>
        internal static string ContactUS {
            get {
                return ResourceManager.GetString("ContactUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; جميع الحقوق محفوظة لشركة ديجيتال تاجز 2015.
        /// </summary>
        internal static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني:.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسئلة شائعة.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرض الصور.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفنادق.
        /// </summary>
        internal static string Hotels {
            get {
                return ResourceManager.GetString("Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LangArabic {
            get {
                return ResourceManager.GetString("LangArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أحدث العروض.
        /// </summary>
        internal static string LatestOffers {
            get {
                return ResourceManager.GetString("LatestOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مناسك.
        /// </summary>
        internal static string ModuleManasek {
            get {
                return ResourceManager.GetString("ModuleManasek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مزارات.
        /// </summary>
        internal static string ModuleMazarat {
            get {
                return ResourceManager.GetString("ModuleMazarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العروض.
        /// </summary>
        internal static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string OtherLanguageId {
            get {
                return ResourceManager.GetString("OtherLanguageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رحــلاتنا.
        /// </summary>
        internal static string OurTrips {
            get {
                return ResourceManager.GetString("OurTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقة الاعمال.
        /// </summary>
        internal static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل الصور.
        /// </summary>
        internal static string PortfolioAllItems {
            get {
                return ResourceManager.GetString("PortfolioAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pull-right.
        /// </summary>
        internal static string PullClass {
            get {
                return ResourceManager.GetString("PullClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدماتنا.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السكينة للسياحة.
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;اكتشف العالم مع  &lt;span class=&quot;colortext&quot;&gt;السكينة للسياحة&lt;/span&gt; &lt;/h1&gt;.
        /// </summary>
        internal static string SiteSlogan {
            get {
                return ResourceManager.GetString("SiteSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحلول.
        /// </summary>
        internal static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشرفون.
        /// </summary>
        internal static string Supervisors {
            get {
                return ResourceManager.GetString("Supervisors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التليفون :.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيديوهات.
        /// </summary>
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        internal static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحبا بكم مع السكينة للسياحة.
        /// </summary>
        internal static string WelcomeBoxTitle {
            get {
                return ResourceManager.GetString("WelcomeBoxTitle", resourceCulture);
            }
        }
    }
}
