//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Items {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Items() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Items", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقالات.
        /// </summary>
        internal static string AllItems {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الصوتي.
        /// </summary>
        internal static string AudioExtension {
            get {
                return ResourceManager.GetString("AudioExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكاتب.
        /// </summary>
        internal static string AuthorID {
            get {
                return ResourceManager.GetString("AuthorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكاتب.
        /// </summary>
        internal static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        internal static string CategoryID {
            get {
                return ResourceManager.GetString("CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        internal static string DepartmentID {
            get {
                return ResourceManager.GetString("DepartmentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text1.
        /// </summary>
        internal static string ExtraText_1 {
            get {
                return ResourceManager.GetString("ExtraText_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاكس.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        internal static string FileExtension {
            get {
                return ResourceManager.GetString("FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط العرض.
        /// </summary>
        internal static string GoogleLatitude {
            get {
                return ResourceManager.GetString("GoogleLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط الطول.
        /// </summary>
        internal static string GoogleLongitude {
            get {
                return ResourceManager.GetString("GoogleLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطول.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض على الموقع.
        /// </summary>
        internal static string IsAvailable {
            get {
                return ResourceManager.GetString("IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئيسي.
        /// </summary>
        internal static string IsMain {
            get {
                return ResourceManager.GetString("IsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المراجعة.
        /// </summary>
        internal static string IsReviewed {
            get {
                return ResourceManager.GetString("IsReviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        internal static string ItemDate {
            get {
                return ResourceManager.GetString("ItemDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنتهاء.
        /// </summary>
        internal static string ItemEndDate {
            get {
                return ResourceManager.GetString("ItemEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقالات.
        /// </summary>
        internal static string ItemsBoxHeader {
            get {
                return ResourceManager.GetString("ItemsBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقالات.
        /// </summary>
        internal static string ItemsModuleTitle {
            get {
                return ResourceManager.GetString("ItemsModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان.
        /// </summary>
        internal static string ItemText {
            get {
                return ResourceManager.GetString("ItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق البريد.
        /// </summary>
        internal static string MailBox {
            get {
                return ResourceManager.GetString("MailBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكلمات المفتاحية.
        /// </summary>
        internal static string MetaKeyWords {
            get {
                return ResourceManager.GetString("MetaKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجوال.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الرسائل.
        /// </summary>
        internal static string Module_AllMessage {
            get {
                return ResourceManager.GetString("Module_AllMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة تصنيف.
        /// </summary>
        internal static string Module_CategoriesAdd {
            get {
                return ResourceManager.GetString("Module_CategoriesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيفات.
        /// </summary>
        internal static string Module_CategoriesDefault {
            get {
                return ResourceManager.GetString("Module_CategoriesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل تصنيف.
        /// </summary>
        internal static string Module_CategoriesEdit {
            get {
                return ResourceManager.GetString("Module_CategoriesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات.
        /// </summary>
        internal static string Module_Comments {
            get {
                return ResourceManager.GetString("Module_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات المفعلة.
        /// </summary>
        internal static string Module_CommentsActive {
            get {
                return ResourceManager.GetString("Module_CommentsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليقات غير المفعلة.
        /// </summary>
        internal static string Module_CommentsInactive {
            get {
                return ResourceManager.GetString("Module_CommentsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير البيانات.
        /// </summary>
        internal static string Module_ExportData {
            get {
                return ResourceManager.GetString("Module_ExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string Module_ItemsAdd {
            get {
                return ResourceManager.GetString("Module_ItemsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        internal static string Module_ItemsDefault {
            get {
                return ResourceManager.GetString("Module_ItemsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Module_ItemsEdit {
            get {
                return ResourceManager.GetString("Module_ItemsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصور.
        /// </summary>
        internal static string Module_ItemsPhotos {
            get {
                return ResourceManager.GetString("Module_ItemsPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة صورة.
        /// </summary>
        internal static string Module_ItemsPhotosAdd {
            get {
                return ResourceManager.GetString("Module_ItemsPhotosAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الرسالة.
        /// </summary>
        internal static string Module_MessageData {
            get {
                return ResourceManager.GetString("Module_MessageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد الرسائل.
        /// </summary>
        internal static string Module_NewMessage {
            get {
                return ResourceManager.GetString("Module_NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزيد.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoreItems.gif.
        /// </summary>
        internal static string MoreItems {
            get {
                return ResourceManager.GetString("MoreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض للمسجلين فقط.
        /// </summary>
        internal static string OnlyForRegisered {
            get {
                return ResourceManager.GetString("OnlyForRegisered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة 2.
        /// </summary>
        internal static string Photo2Extension {
            get {
                return ResourceManager.GetString("Photo2Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        internal static string PhotoExtension {
            get {
                return ResourceManager.GetString("PhotoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الألبوم.
        /// </summary>
        internal static string PhotoPageItems {
            get {
                return ResourceManager.GetString("PhotoPageItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أولوية العرض.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishAudio {
            get {
                return ResourceManager.GetString("PublishAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishFile {
            get {
                return ResourceManager.GetString("PublishFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishPhoto {
            get {
                return ResourceManager.GetString("PublishPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishPhoto2 {
            get {
                return ResourceManager.GetString("PublishPhoto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishVideo {
            get {
                return ResourceManager.GetString("PublishVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشر.
        /// </summary>
        internal static string PublishYoutbe {
            get {
                return ResourceManager.GetString("PublishYoutbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد الرسائل.
        /// </summary>
        internal static string RequestNewCount {
            get {
                return ResourceManager.GetString("RequestNewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسائل.
        /// </summary>
        internal static string RequestTotalCount {
            get {
                return ResourceManager.GetString("RequestTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال إميلات.
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        internal static string SenderCountry {
            get {
                return ResourceManager.GetString("SenderCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string SenderEMail {
            get {
                return ResourceManager.GetString("SenderEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم.
        /// </summary>
        internal static string SenderName {
            get {
                return ResourceManager.GetString("SenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال رسائل قصيرة.
        /// </summary>
        internal static string SendSms {
            get {
                return ResourceManager.GetString("SendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملخص.
        /// </summary>
        internal static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مميز.
        /// </summary>
        internal static string SpecialOption {
            get {
                return ResourceManager.GetString("SpecialOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        internal static string Tels {
            get {
                return ResourceManager.GetString("Tels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع الأول.
        /// </summary>
        internal static string Type_1 {
            get {
                return ResourceManager.GetString("Type_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع الثاني.
        /// </summary>
        internal static string Type_2 {
            get {
                return ResourceManager.GetString("Type_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع الثالث.
        /// </summary>
        internal static string Type_3 {
            get {
                return ResourceManager.GetString("Type_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع الرابع.
        /// </summary>
        internal static string Type_4 {
            get {
                return ResourceManager.GetString("Type_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع الخامس.
        /// </summary>
        internal static string Type_5 {
            get {
                return ResourceManager.GetString("Type_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل المقال.
        /// </summary>
        internal static string UpdateItems {
            get {
                return ResourceManager.GetString("UpdateItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف المرئي.
        /// </summary>
        internal static string VideoExtension {
            get {
                return ResourceManager.GetString("VideoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الزيارات.
        /// </summary>
        internal static string VisitiesCount {
            get {
                return ResourceManager.GetString("VisitiesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العرض.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود ملف اليوتيوب.
        /// </summary>
        internal static string YoutubeCode {
            get {
                return ResourceManager.GetString("YoutubeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز البريدي.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
